---
# vim: set sw=2 ts=2 et:
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: 'v2.3.0'
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-symlinks
      - id: check-toml
      - id: trailing-whitespace
      - id: mixed-line-ending
        args:
          - --fix=no
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.15.0
    hooks:
      - id: yamllint
  - repo: https://github.com/godaddy/tartufo
    rev: v2.0.1
    hooks:
      - id: tartufo